#!/usr/bin/zsh

# If you run multiple tmux sessions, each containing multiple windows, then
# this script will help you jump from one to another.
# Sample tmux binding:
#   bind-key \; new-window -n 'switcher' "tpick_tmux"

if [[ -z $TMUX ]]
then
   print "error: we require tmux" >&2
   return 1
fi

local session target
local -a targets

for session in $(tmux list-sessions -F "#{session_name}" | sort)
do
   tmux list-windows -t $session -F "#{session_name}:#{window_name}"
done | grep -v ':switcher\>' | tr '\n' ' ' | read -A targets

target=$(tpick -f "main" $targets) || return 1

tmux switch-client -t ${target%%:*}
tmux select-window -t $target

